global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: speedtest
    honor_timestamps: true
    scrape_interval: 30m
    scrape_timeout: 1m
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - speedtest-exporter:9798
  - job_name: secondary_speedtest
    honor_timestamps: true
    scrape_interval: 30m
    scrape_timeout: 1m
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - 192.168.1.32:9798
    metric_relabel_configs:
      - source_labels: [ __name__ ]
        regex: (.*)
        target_label: __name__
        replacement: secondary_$1
  - job_name: ping
    honor_timestamps: true
    params:
      module:
        - http_2xx
    scrape_interval: 30s
    scrape_timeout: 30s
    metrics_path: /probe
    scheme: http
    follow_redirects: true
    enable_http2: true
    relabel_configs:
      - source_labels: [__address__]
        separator: ;
        regex: (.*);(.*)
        target_label: instance
        replacement: $1
        action: replace
      - source_labels: [__address__]
        separator: ;
        regex: (.*);(.*)
        target_label: humanname
        replacement: $2
        action: replace
      - source_labels: [instance]
        separator: ;
        regex: (.*)
        target_label: __param_target
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: blackbox-exporter:9115
        action: replace
    file_sd_configs:
      - files:
          - /etc/prometheus/pinghosts.yaml
        refresh_interval: 5m
  - job_name: secondary_ping
    honor_timestamps: true
    params:
      module:
        - http_2xx
    scrape_interval: 30s
    scrape_timeout: 30s
    metrics_path: /probe
    scheme: http
    follow_redirects: true
    enable_http2: true
    relabel_configs:
      - source_labels: [ __address__ ]
        separator: ;
        regex: (.*);(.*)
        target_label: instance
        replacement: $1
        action: replace
      - source_labels: [ __address__ ]
        separator: ;
        regex: (.*);(.*)
        target_label: humanname
        replacement: $2
        action: replace
      - source_labels: [ instance ]
        separator: ;
        regex: (.*)
        target_label: __param_target
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: 192.168.1.32:9115
        action: replace
    metric_relabel_configs:
      - source_labels: [ __name__ ]
        regex: (.*)
        target_label: __name__
        replacement: secondary_$1
    file_sd_configs:
      - files:
          - /etc/prometheus/pinghosts.yaml
        refresh_interval: 5m