version: '1'

services:
  speedtest-exporter:
    image: miguelndecarvalho/speedtest-exporter
    container_name: speedtest-exporter
    restart: unless-stopped
    ports:
      - '9798:9798'

  blackbox-exporter:
    build:
      context: .
      dockerfile: blackbox-exporter.Dockerfile
    container_name: blackbox-exporter
    restart: unless-stopped
    ports:
      - '9115:9115'